global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8083']

  - job_name: 'didactic-config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['didactic-config-server:8888']

  - job_name: 'didactic-personal'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['didactic-personal:8080']

  - job_name: 'catalogue'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['catalogue:8081']

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s